### ISSUE TITLE
Add mprsa

### ISSUE THREAD

**Issue by git-n-pissed** [mcauser/awesome-micropython#100]
[mprsa](https://github.com/git-n-pissed/mprsa) - A MicroPython module for creating, importing, and exporting RSA keys in DER and PEM formats with PKCS#1, PKCS#8, and X.509/SPKI structures, and signing/verifying and encryption/decryption using blinding and SHA-1 and SHA-256 hashing algorithms.

**Comment by mcauser** [comment]
Added in https://github.com/mcauser/awesome-micropython/commit/5e347a23dc35f43dcc7456e40a38d4086267122d

Cheers @git-n-pissed 🍻
