### ISSUE TITLE
Suggestion: SH1107 display driver with support for 128 x 128 pixel OLEDs

### ISSUE THREAD

**Issue by peter-l5** [mcauser/awesome-micropython#106]
Besides support for 128 x 64 displays provided by the SH1107 driver already listed, this one also supports 128 x 128 displays. It works with I2C and SPI and provides for initialisation in different rotations, some optimisations for partial screen updates, and support for hardware features such as flipping the display upside down. 

[SH1107](https://github.com/peter-l5/SH1107 'SH1107 display driver') - Micropython driver for SH1107-based OLED displays, both 128 x 128 and 128 x 64 pixels

**Comment by mcauser** [comment]
Looks like you have a few other drivers to that could make the list, DS1307, SCD4X, framebuf2, etc

**Comment by peter-l5** [comment]
Certainly, then, I will look to submit a pull request or two over the coming days.
