### ISSUE TITLE
sht11 module for micropython

### ISSUE THREAD

**Issue by 2black0** [mcauser/awesome-micropython#11]
I propose module to read sht11 sensor for esp32 (maybe esp8266 too)
modified from https://github.com/ayoy/upython-aq-monitor which only pyboard supported

link of sht11 module: https://github.com/2black0/micropython-sht11

it will be great if listed :)
thanks

**Comment by askpatrickw** [comment]
You can always submit a PR

https://github.com/mcauser/awesome-micropython/blob/master/contributing.md

**Comment by mcauser** [comment]
Added in https://github.com/mcauser/awesome-micropython/commit/32ec1399dc7983d26db59e3800aac9771fe7e3a5
