### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ndsvw** [mcauser/awesome-micropython#113]
Hi, I found a broken link:
- [ ] https://github.com/thebaron88/micropython_quickled (file: README.md, status code: 404)

**Comment by andypiper** [comment]
Thanks for noticing and reporting. I am having trouble figuring out if this has gone away completely or moved elsewhere. It looks like for now it doesn't qualify as "awesome" since we can't find it 😞 so I'll go ahead and raise a PR to remove.
