### ISSUE TITLE
LVGL?

### ISSUE THREAD

**Issue by amirgon** [mcauser/awesome-micropython#12]
Do you think LVGL Micropython binding could fit in your list?

https://docs.lvgl.io/latest/en/html/get-started/micropython.html

https://hackaday.com/2019/02/28/littlevgl-brings-gui-tools-to-micropython/

https://hackaday.com/2019/08/31/micropython-and-c-play-together-better/

**Comment by mcauser** [comment]
Added in https://github.com/mcauser/awesome-micropython/commit/240bc063d85db01b04b24252d8e97adb7dbf50f6
