### ISSUE TITLE
Add Husky Lens drivers

### ISSUE THREAD

**Issue by QuirkyCort** [mcauser/awesome-micropython#126]
This is a driver for the DFRobot Husky Lens. https://github.com/QuirkyCort/IoTy/blob/main/public/extensions/huskylib.py

The Husky Lens (https://www.dfrobot.com/product-1922.html) is a camera module that can do some onboard machine vision tasks and returns the results in either UART or I2C mode.

The driver is based on the official Python API (https://github.com/HuskyLens/HUSKYLENSPython), but heavily modified to work with micropython and fix a few bugs.

This driver was written for the IoTy project (...a web-based blocks to Python system, similar to BIPES), so it doesn't have it's own repository.

**Comment by mcauser** [comment]
Thanks @QuirkyCort Added in 78f0bce80ca5f957fbcd7457a9a15961ccf7dab3
