### ISSUE TITLE
Add TCA9548A drivers

### ISSUE THREAD

**Issue by QuirkyCort** [mcauser/awesome-micropython#127]
This is a driver for the TCA9548A (I2C multiplexer). https://github.com/QuirkyCort/IoTy/blob/main/public/extensions/tca9548a.py

This is a really trivial driver, but I suppose it may be useful to some.

This driver was written for the IoTy project (...a web-based blocks to Python system, similar to BIPES), so it doesn't have it's own repository.

**Comment by mcauser** [comment]
Thanks @QuirkyCort added in 631045d7037c4e957c3bbad78806ac016f7fd15d
