### ISSUE TITLE
Suggestion: Add utility to freeze file system and allow to mount it

### ISSUE THREAD

**Issue by bixb922** [mcauser/awesome-micropython#129]
https://github.com/bixb922/freezeFS

freezeFS

freezes file structures on the PC with text and binary files into Python source for freezing as bytecode in flash. It allows to mount the frozen data as a read-only Virtual File System, or to extract the files to the flash file system.

Category : Flash

**Comment by mcauser** [comment]
Thanks @bixb922, added in 1d8f9005e2590a69d83c24911be37f7eef1c3ee9
