### ISSUE TITLE
Add micropython-generic-thermistor

### ISSUE THREAD

**Issue by Trexation** [mcauser/awesome-micropython#133]
Would you be willing to add my library to the ADC temperature sensor section? 
Thanks!

[micropython-generic-thermistor](https://github.com/Trexation/micropython-generic-thermistor) - Micropython Generic Thermistor Library is a basic software module designed to simplify temperature sensing using NTC thermistors within MicroPython-based projects. The library assumes a generic NTC thermistor on the ground side of a voltage divider.

**Comment by mcauser** [comment]
Thanks @Trexation, added in 69b12614cc1a521ab8d9dd237e467bc22c4fc7f9
