### ISSUE TITLE
Add LD2410 Human Presence Sensor

### ISSUE THREAD

**Issue by QuirkyCort** [mcauser/awesome-micropython#134]
This is a driver for the LD2410. https://github.com/QuirkyCort/IoTy/blob/main/public/extensions/ld2410.py

This is a 24GHz human presence sensing module, capable of detecting moving and stationary targets, and provide an approximate range.

This driver was written for the IoTy project (...a web-based blocks to Python system, similar to BIPES), so it doesn't have it's own repository.

**Comment by mcauser** [comment]
Thanks @QuirkyCort added in 6d92d4e37fd50c6cacc856f3e8c07ccb9d81e42a
