### ISSUE TITLE
Add YX5300 Serial MP3 Player

### ISSUE THREAD

**Issue by QuirkyCort** [mcauser/awesome-micropython#135]
This is a driver for the YX5300. https://github.com/QuirkyCort/IoTy/blob/main/public/extensions/yx5300.py

This is an MP3 player that can be controlled via a serial interface.

This driver was written for the IoTy project (...a web-based blocks to Python system, similar to BIPES), so it doesn't have it's own repository.

**Comment by mcauser** [comment]
Thanks @QuirkyCort added in 76924053d43f4769a56bbffe570b861dbae1d949
