### ISSUE TITLE
Add amazon.com to BOT_ALLOW_LIST for awesome_bot workflow

### ISSUE THREAD

**Issue by andypiper** [mcauser/awesome-micropython#146]
Per this [run](https://github.com/mcauser/awesome-micropython/actions/runs/8450545506/job/23146934719?pr=144), it looks like amazon.com is potentially (?) sending HTTP 403 for valid links, from runs of the workflow that checks links. May be worth adding to the environment variable for the workflow to skip.

**Comment by mcauser** [comment]
Thanks @andypiper fixed in https://github.com/mcauser/awesome-micropython/pull/148
Including bumping ruby + node versions
