### ISSUE TITLE
mpsync - A tool that detects changes in files and synchronizes them to a micropython board

### ISSUE THREAD

**Issue by Uhlo** [mcauser/awesome-micropython#15]
Hi,

I'm new to micropython and for my workflow I created a tool that detects changes to files in a specified folder and synchronizes them to a micropython board. That way, whenever you save your project, your board directly executes what you've just written.

The project is called [mpsync](https://github.com/Uhlo/mpsync), is licensed under the MIT license and can be downloaded via pip (`pip install mpsync`). It is in very early development and has definitely some missing features.

Maybe this tool is also helpful for other developers, so it would be great if it can be added to this list. I'm not sure under wich topic it would fit. It runs on the host, but is not really a shell.

Best,
Uhlo

**Comment by askpatrickw** [comment]
Hey @Uhlo  Just submit a PR and  you can add it. Simple markdown edit will do it. 
https://github.com/mcauser/awesome-micropython/blob/master/contributing.md

Then the Rep owner will review.

**Comment by Uhlo** [comment]
Thanks, I will do that. Any tip on which topic fits for the tool?

**Comment by mcauser** [comment]
Thanks @askpatrickw and @Uhlo
