### ISSUE TITLE
dead links in the micropyton display driver list

### ISSUE THREAD

**Issue by Flaming-crossbow** [mcauser/awesome-micropython#21]
Hey, i am setting up a [reference chart](https://github.com/Flaming-crossbow/Micropython-with-ESP8266-ESP32-W600-Pi-Pico-etc/blob/main/readme.md) for micropython display drivers and unfortunately i came across some dead links on your website/github. Do you happen to have new sources for the drivers?

|Controller |Type|Typical display |conn.|Typ.res.|Driver Library |Remark |
|----|----|----|----|----|----|----|
Dead link|SSD1606 |E-Paper|active matrix epaper| |128x180|[micropython-ili9341 ](https://bitbucket.org/thesheep/micropython-ili9341)|Collection of drivers |
Dead link|ILI9341|LCD TFT|Medium lcd rgb 2.7”-3.2” | | |[micropython-ili9341](https://bitbucket.org/thesheep/micropython-ili9341)|Collection of drivers |
Dead link|SH1106|LCD TFT| | | |[micropython-ili9341](https://bitbucket.org/thesheep/micropython-ili9341)|Collection of drivers |
Dead link|SSD1606|LCD TFT| | | |[micropython-ili9341](https://bitbucket.org/thesheep/micropython-ili9341)|Collection of drivers |
Dead link|ST7735|LCD TFT| | | |[micropython-ili9341](https://bitbucket.org/thesheep/micropython-ili9341)|Collection of drivers |
Dead link|PCD8544|OLED| | | |[micropython-oled](https://bitbucket.org/thesheep/micropython-oled)|Collection of drivers |
Dead link|SH1106|OLED| | | |[micropython-oled](https://bitbucket.org/thesheep/micropython-oled)|Collection of drivers |
Dead link|SSD1306|OLED| | | |[micropython-oled](https://bitbucket.org/thesheep/micropython-oled)|Collection of drivers |
Dead link|UC1701X|OLED| | | |[micropython-oled](https://bitbucket.org/thesheep/micropython-oled)|Collection of drivers |

**Comment by mcauser** [comment]
Hey, thanks for reporting.
These are Deshipu's old mercurial repos. Bitbucket [dropped support for mercurial](https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket). You can find an [archive of them here](https://bitbucket-archive.softwareheritage.org/projects/th/thesheep/).

I'll ask him if there are mirrored anywhere and update the links.

**Comment by mcauser** [comment]
I've forked each and updated the links
