### ISSUE TITLE
MicroWebSrv2 library

### ISSUE THREAD

**Issue by jczic** [mcauser/awesome-micropython#3]
Hello,
About your awesome MicroPython list, I see mainly drivers for sensors but I read "libraries, frameworks, software and resources" :)
I can purpose the new version of a micro HTTP Web Server with modules : **MicroWebSrv2**

GitHub repository at https://github.com/jczic/MicroWebSrv2 (**[see features](https://github.com/jczic/MicroWebSrv2#features)**)
Page at https://MicroWebSrv2.hc2.fr

Do you think this library would be worth adding?
Thank you. 👍

**Comment by mcauser** [comment]
Looks good! I'll get it added.

**Comment by askpatrickw** [comment]
@jczic Did you submit a PR... ;-) You can see how in the contributing.md in the repo.

**Comment by mcauser** [comment]
Hi @jczic I've added it now.
