### ISSUE TITLE
Using Awesome Micropython with Raspberry Pi Pico

### ISSUE THREAD

**Issue by MyVanitar** [mcauser/awesome-micropython#30]
Hello,

How can I install and use the libraries with the Pico board?

**Comment by mcauser** [comment]
Hi,
You should be able to find useful details inside the readme of each linked repository.
I personally download or fork and clone a repo, transfer the files with [ampy](https://pypi.org/project/adafruit-ampy/), [rshell](https://github.com/dhylands/rshell) or the new [mpremote](https://pypi.org/project/mpremote/).
If you're after a GUI, try [Thonny](https://thonny.org/) or [Mu](https://codewith.mu/).
