### ISSUE TITLE
MicroPython-multiaxis, new path

### ISSUE THREAD

**Issue by OlivierLenoir** [mcauser/awesome-micropython#31]
Hello, I've changed my username on GitLab to comply with SSL requirements.
Project 'olivier.len02/micropython-multiaxis' was moved to 'olivierlenoir/micropython-multiaxis'. Please update any links and bookmarks that may still have the old path.
So correct link is now 'https://gitlab.com/olivierlenoir/micropython-multiaxis'.

**Comment by mcauser** [comment]
Fixed at 01c6d2ea07f2ddaa4b862e11a8b3266d7d3a96a5
