### ISSUE TITLE
First item in **IO-Expander** section is not micropython, but C.

### ISSUE THREAD

**Issue by 5roop** [mcauser/awesome-micropython#36]
Hi, I noticed the following item is not a micropython driver:

> MCP23017-ESP8266-Miniature-Driver - Driver for MCP23017 16-bit I/O Expander.

In my opinion it should be dropped from the list.
Hope it helps.

**Comment by mcauser** [comment]
I agree. Will remove.

**Comment by mcauser** [comment]
Fixed in fe7afb177546cc513e3b46ff07f98bdf8e8b2675
