### ISSUE TITLE
A MicroPython module for asyncio button.

### ISSUE THREAD

**Issue by jacklinquan** [mcauser/awesome-micropython#42]
Hi @mcauser ,
Here's a MicroPython module for asyncio button written by me.
I think it could be useful for projects using asyncio.
https://github.com/jacklinquan/micropython-aiobutton

**Comment by beyonlo** [comment]
@jacklinquan 

Nice module :)

Great work!

**Comment by mcauser** [comment]
Added in https://github.com/mcauser/awesome-micropython/commit/6509fed57bed90b801f050ed61bc5e908893d3db
