### ISSUE TITLE
[MicroPython-NeuralNetwork] - (https://gitlab.com/olivierlenoir/MicroPython-NeuralNetwork) - Neural Network for MicroPython

### ISSUE THREAD

**Issue by OlivierLenoir** [mcauser/awesome-micropython#49]
In category AI.

[MicroPython-NeuralNetwork] - (https://gitlab.com/olivierlenoir/MicroPython-NeuralNetwork) - Neural Network for MicroPython

README
Neural Network using an ESP32 with MicroPython

This repository require using Matrix:
https://gitlab.com/olivierlenoir/MicroPython-Matrix

PROCESS
1 - Train neural network with python
    cd micropython
    python3 test_neuralnetwork

2 - Use neuralnetwork with micropython
    import utest_neuralnetwork

DOCUMENTATION
https://olivierlenoir.gitlab.io/MicroPython-NeuralNetwork/MicroPythonNeuralNetwork.pdf

**Comment by mcauser** [comment]
Thanks @OlivierLenoir 
Added in https://github.com/mcauser/awesome-micropython/commit/3c59088b927a14fb5c63f8dec4654e26553927ea + https://github.com/mcauser/awesome-micropython/commit/3c59088b927a14fb5c63f8dec4654e26553927ea
