### ISSUE TITLE
Micropython video+written tutorials

### ISSUE THREAD

**Issue by bhavesh-k** [mcauser/awesome-micropython#56]
Two great sources of tutorials for Micropython:

1. Miguel Grinberg's 6-part Micropython course. He also created the awesome Microdot library, which allows you to use a Flask-like expressive web framework in Micropython.
https://blog.miguelgrinberg.com/post/micropython-and-the-internet-of-things-part-i-welcome
https://github.com/miguelgrinberg/microdot

2. Bi-weekly Micropython video+written tutorials (full disclosure: this is me...but the tutorials are free, so it's win-win :)
https://bhave.sh

**Comment by andypiper** [comment]
Agree that these are really good resources, and I definitely think that yours qualify as "awesome". I'll see about sending a PR to @mcauser to add these, unless someone else beats me to it...

**Comment by mcauser** [comment]
Thanks @bhavesh-k and @andypiper

[miguelgrinberg/microdot](https://github.com/miguelgrinberg/microdot) was already in there :+1:

Added a link to Miguel's awesome IoT tutorials in https://github.com/mcauser/awesome-micropython/commit/8f0a77728299c3c8eabe4cbb6c722463217e1256

Added link to Bhavesh's awesome series in https://github.com/mcauser/awesome-micropython/commit/4a1114ad8097bd96ab8132c73a49d0fdd101413c
