### ISSUE TITLE
IO-Expander menu has ADC/DAC URL

### ISSUE THREAD

**Issue by beyonlo** [mcauser/awesome-micropython#58]
On the `IO-Expander` menu has the:

[micropython-pcf8591](https://gitlab.com/cediddi/micropython-pcf8591) - MicroPython driver for PCF8591 8-Bit I2C I/O Expander.

But the that url is about ADC/DAC, not about IO Expander.

**Comment by andypiper** [comment]
It's an ADC that can be connected over I2C and also has DAC. I'll move it to the ADC section of the list as that might be a better spot.
