### ISSUE TITLE
there is no micro:bit section

### ISSUE THREAD

**Issue by rhubarbdog** [mcauser/awesome-micropython#76]
the microbit rus so slowly that one wire protocol solution have to be written in arm thumb assembly language and won't easily port to other micropython boards even if there were the need for an assembly solution to getting a sensor to work. 
With version 1 microbits there were issues with the size of program source, this is still the case with version 2, less than 20kb so the microbit version of a sensor is often rendered unreadable by minifying all function and variable names.

do you want to start a microbit section on your awesome list, this is a list i host?
https://github.com/rhubarbdog/microbit-component

**Comment by mcauser** [comment]
Hey, there is already an awesome microbit list: https://github.com/carlosperate/awesome-microbit

I noticed you're pointing to Deshipu's old ht16k33 bitbucket repo. It's since been removed, but I have a backup here:
https://github.com/mcauser/deshipu-micropython-ht16k33
