### ISSUE TITLE
Proposing a new section "Frameworks"

### ISSUE THREAD

**Issue by amotl** [mcauser/awesome-micropython#8]
Dear Mike,

thanks for your awesome collection of MicroPython resources - and also thanks to all of the contributors.

We would like to add the [Terkin Datalogger](https://github.com/hiveeyes/terkin-datalogger) to the collection. However, it is not quite a library but would probably qualify as a "full program".

While thinking about that, the naming would be a bit awkward, so we came up with "Frameworks" which we believe would fit better. We have a strong background using the [Pyramid web framework](https://trypyramid.com/) which could be seen as a role model for Terkin somehow - naturally on a much smaller scale ;].

Thanks already for looking into this. We wanted to humbly ask about your opinion on that before actually starting a pull request.

With kind regards,
Andreas.

**Comment by mcauser** [comment]
Hi @amotl 
I think adding a new top level section **Frameworks** makes sense.
There's a few others that could be moved across, web frameworks, smart home etc.

**Comment by mcauser** [comment]
Added in https://github.com/mcauser/awesome-micropython/commit/83a0e031c3786e97e7446c913c2d539d941b335b

**Comment by amotl** [comment]
Dear Mike,

thank you so much. We feel honored to see the Terkin Datalogger in the list of the Awesome MicroPython collection you are curating here.

With kind regards,
Andreas.
