### ISSUE TITLE
Suggestion: Set up a cron CI workflow to check links

### ISSUE THREAD

**Issue by carlosperate** [mcauser/awesome-micropython#82]
Just a suggestion in case you are interested, on my Awesome list I run a workflow like this to check for dead links every morning:
https://github.com/carlosperate/awesome-microbit/blob/master/.github/workflows/check-links.yml

It uses a ruby-base awesome list tool instea of the more common awesome-lint, as I find some of the awesome-link rules a bit too strick and awesome_bot works well for my purposes.

The workflow file would likely Just Work™️ if it's copy/pasted, happy to submit a PR if it's something you'd like to integrate here as well.

**Comment by andypiper** [comment]
Related - #81 updates the content to fix redirects and dead links. I agree that hooking this up with CI would be useful. 

(👋🏻 @carlosperate we should carry on that conversation we started at EuroPython!)

**Comment by carlosperate** [comment]
Great, thanks for fixing links already, it will make a PR for this easier! I'll submit something for review 👍 

And yes, let's catch up some time! In the end we haven't set up the Oxford Python group yet, but I'll let you know when get something going as well 😃

It's a bit early in the morning tomorrow, but maybe I'll try to catch the Melbourne MicroPython session via Zoom as well.

**Comment by carlosperate** [comment]
PR:
- https://github.com/mcauser/awesome-micropython/pull/86

**Comment by mcauser** [comment]
Merged, finally. Thanks 😄
