### ISSUE TITLE
Add mpbridge CLI tool

### ISSUE THREAD

**Issue by AmirHmZz** [mcauser/awesome-micropython#83]
I'm maintainer of [mpbridge](https://github.com/AmirHmZz/mpbridge) CLI tool which helps MicroPython developers to develop and debug faster and easier. This tool can be integrated into any IDE and help you sync / run / debug project faster. It depends on mpremote which is officially maintained by MicroPython organization.

**Comment by andypiper** [comment]
Thanks! I actually added this in #79 a week or so ago - it is in the CLI section. 👍🏻

**Comment by AmirHmZz** [comment]
Wow :D thank you. I've checked it 3 weeks ago and I thought It's still missing here.
